package ru.pominov.service;

import ru.pominov.config.AppLogger;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

// Тестовый класс для создания таблицы Books
public class TableCreator {

    private static final Logger LOGGER = AppLogger.getLogger();

    public void createTable(Connection connection) {
        try (Statement statement = connection.createStatement()) {

            String createTableSql = "CREATE TABLE books (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "author VARCHAR(100)," +
                    "title VARCHAR(150)," +
                    "publish_date VARCHAR(50)," +
                    "description VARCHAR(2000)" +
                    ")";

            statement.executeUpdate(createTableSql);
            LOGGER.log(Level.INFO, "Created table 'books'");

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Connection to database refused", e);
        }
    }
}
